import { randomBytes, timingSafeEqual } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { createServer, type Server, type Socket } from "node:net";
import { join } from "node:path";
import { sanitizeCookies, type SessionCookie } from "../src/shared/youtube-cookies";

/** A browser profile connected through the Nixie extension, as the sign-in screen shows it. */
export interface ExtensionConnection {
	/** Opaque, generated by the extension. The only thing that tells two profiles apart. */
	installId: string;
	/** For display only, the browser's own brand. */
	browser: string;
	/** Whether that profile holds a YouTube session at all. A signed-out row is shown and refused. */
	signedIn: boolean;
}

// A line past this is a peer that is not our host, so it is dropped rather than buffered.
const MAX_LINE = 256 * 1024;
// More than a handful of browsers connected at once is not a real desktop, it is something wrong.
const MAX_CONNECTIONS = 8;
const INSTALL_ID = /^[0-9a-f-]{36}$/;
const BROWSERS = new Set(["Google Chrome", "Microsoft Edge", "Brave", "Vivaldi", "Opera", "Chromium", "Chrome"]);

interface Connection extends ExtensionConnection {
	socket: Socket;
}

/**
 * The one inbound surface this app has. A browser extension reads its own YouTube cookies and hands
 * them here through the native host, which connects to a per-user pipe. On macOS and Linux the socket
 * sits inside a `0o700` userData directory and the token is belt and braces; on Windows a named pipe
 * carries a default DACL that lets any local process connect and node exposes no way to set one, so
 * the pipe name is randomised per install and the first line has to carry a token only this user can
 * read (the config file is `0o600` inside their own profile). Nothing confidential travels outward on
 * this pipe: the app sends pull requests and never a cookie, so a process that guessed both could
 * offer this app a session and could never take one from it.
 */
export class NativeHostServer {
	readonly #connections = new Map<string, Connection>();
	readonly #pending = new Map<
		number,
		{ resolve: (cookies: SessionCookie[]) => void; timer: ReturnType<typeof setTimeout> }
	>();
	readonly #listeners = new Set<(connections: ExtensionConnection[]) => void>();
	#server: Server | undefined;
	#token = "";
	#pipe = "";
	#allowedOrigins: string[] = [];
	#nextId = 1;

	/** The pipe path and the token the native host manifest points the browser at. */
	get config() {
		return { pipe: this.#pipe, token: this.#token, allowedOrigins: this.#allowedOrigins };
	}

	async listen(userDataPath: string, allowedOrigins: string[]) {
		this.#allowedOrigins = allowedOrigins;
		this.#token = randomBytes(32).toString("base64url");
		this.#pipe =
			process.platform === "win32"
				? `\\\\.\\pipe\\nixie-${randomBytes(8).toString("hex")}`
				: join(userDataPath, "native-host", "nixie-host.sock");
		const dir = join(userDataPath, "native-host");
		await mkdir(dir, { recursive: true, mode: 0o700 });
		await writeFile(join(dir, "config.json"), JSON.stringify(this.config), { mode: 0o600 });

		await new Promise<void>((resolve, reject) => {
			this.#server = createServer((socket) => this.#accept(socket));
			this.#server.on("error", reject);
			this.#server.listen(this.#pipe, resolve);
		});
	}

	connections(): ExtensionConnection[] {
		return [...this.#connections.values()].map(({ installId, browser, signedIn }) => ({
			installId,
			browser,
			signedIn,
		}));
	}

	onChange(listener: (connections: ExtensionConnection[]) => void) {
		this.#listeners.add(listener);
		return () => this.#listeners.delete(listener);
	}

	/** The cookies that profile holds now, pulled through the extension, or a rejection on timeout. */
	async pull(installId: string, timeoutMs = 4000): Promise<SessionCookie[]> {
		const connection = this.#connections.get(installId);
		if (!connection) throw new Error("Extension not connected");
		const id = this.#nextId++;
		return new Promise<SessionCookie[]>((resolve, reject) => {
			const timer = setTimeout(() => {
				this.#pending.delete(id);
				reject(new Error("Extension pull timed out"));
			}, timeoutMs);
			this.#pending.set(id, { resolve, timer });
			connection.socket.write(`${JSON.stringify({ type: "pull", id })}\n`);
		});
	}

	#accept(socket: Socket) {
		let installId: string | undefined;
		let buffer = "";
		let handshaken = false;
		socket.setEncoding("utf8");
		socket.on("data", (chunk: string) => {
			buffer += chunk;
			let index: number;
			while ((index = buffer.indexOf("\n")) !== -1) {
				const line = buffer.slice(0, index);
				buffer = buffer.slice(index + 1);
				if (line.length > MAX_LINE) return socket.destroy();
				let message: unknown;
				try {
					message = JSON.parse(line);
				} catch {
					return socket.destroy();
				}
				if (!handshaken) {
					if (!this.#handshake(message)) return socket.destroy();
					handshaken = true;
					continue;
				}
				installId = this.#dispatch(socket, message) ?? installId;
			}
		});
		socket.on("close", () => {
			if (installId && this.#connections.get(installId)?.socket === socket) {
				this.#connections.delete(installId);
				this.#emit();
			}
		});
		socket.on("error", () => socket.destroy());
	}

	#handshake(message: unknown): boolean {
		if (typeof message !== "object" || message === null) return false;
		const record = message as Record<string, unknown>;
		if (record.v !== 1 || typeof record.origin !== "string" || !this.#allowedOrigins.includes(record.origin)) {
			return false;
		}
		if (typeof record.token !== "string") return false;
		const given = Buffer.from(record.token);
		const expected = Buffer.from(this.#token);
		return given.length === expected.length && timingSafeEqual(given, expected);
	}

	/** Returns the installId a hello registered, so the socket's close can drop it. */
	#dispatch(socket: Socket, message: unknown): string | undefined {
		if (typeof message !== "object" || message === null) return undefined;
		const record = message as Record<string, unknown>;
		if (record.type === "hello") return this.#hello(socket, record);
		if (record.type === "cookies") this.#cookies(record);
		return undefined;
	}

	#hello(socket: Socket, record: Record<string, unknown>): string | undefined {
		const installId = record.installId;
		if (typeof installId !== "string" || !INSTALL_ID.test(installId)) {
			socket.destroy();
			return undefined;
		}
		const browser = typeof record.browser === "string" && BROWSERS.has(record.browser) ? record.browser : "Chromium";
		const signedIn = record.signedIn === true;
		// The hello carries the profile's cookies too, but they are not trusted from the wire: they are
		// validated the same as a pull's answer, and a hello whose cookies are malformed still registers
		// the connection, since the session comes from the pull the link will make in a moment.
		if (this.#connections.size >= MAX_CONNECTIONS && !this.#connections.has(installId)) {
			socket.destroy();
			return undefined;
		}
		this.#connections.get(installId)?.socket.destroy();
		this.#connections.set(installId, { socket, installId, browser, signedIn });
		this.#emit();
		return installId;
	}

	#cookies(record: Record<string, unknown>) {
		const id = record.id;
		if (typeof id !== "number") return;
		const waiter = this.#pending.get(id);
		if (!waiter) return;
		const cookies = sanitizeCookies(record.cookies);
		// A malformed answer is left to time out rather than resolved with a bad session or cleared into
		// silence, which is the same failure a browser that closed mid-pull produces. Only a valid answer
		// settles the promise and cancels its timer.
		if (!cookies) return;
		this.#pending.delete(id);
		clearTimeout(waiter.timer);
		waiter.resolve(cookies);
	}

	#emit() {
		const snapshot = this.connections();
		for (const listener of this.#listeners) listener(snapshot);
	}
}
