import type {
	Album,
	Artist,
	MusicEntity,
	MusicSection,
	Page,
	Playlist,
	PlaylistItem,
	RemoteId,
	Track,
} from "./contracts";
import type { Messages } from "./i18n";

/**
 * Music entities are narrowed by field presence. `PlaylistItem` is checked first because it wraps
 * a `Track` and would otherwise satisfy none of the other predicates cleanly.
 */
export function isPlaylistItem(item: MusicEntity): item is PlaylistItem {
	return "track" in item;
}

export function isTrack(item: MusicEntity): item is Track {
	return "durationSeconds" in item;
}

export function isArtist(item: MusicEntity): item is Artist {
	return "name" in item && !isPlaylistItem(item);
}

export function isAlbum(item: MusicEntity): item is Album {
	return "artists" in item && !isTrack(item) && !isPlaylistItem(item);
}

export function isPlaylist(item: MusicEntity): item is Playlist {
	return "title" in item && !isTrack(item) && !isAlbum(item) && !isPlaylistItem(item);
}

/**
 * A podcast show. Upstream addresses one by an `MPSP` browse id, which is the one unlocalised thing
 * telling it apart from a playlist: it lists, plays and opens exactly like one, and none of a
 * playlist's writes (delete, add to, save to library) are known to accept it.
 */
export function isPodcast(item: MusicEntity): item is Playlist {
	return isPlaylist(item) && item.id.startsWith("MPSP");
}

export function trackAlbumId(track: Track): RemoteId | undefined {
	return track.album?.id ?? track.albumId;
}

/**
 * Where a chart puts an entity. Only a song and an artist are ever charted, and only upstream knows
 * the number: counting rows off instead is wrong the moment a shelf loses one, which every chart
 * shelf does, since its video rows are dropped before the renderer sees them.
 */
export function entityRank(item: MusicEntity): number | undefined {
	const subject = isPlaylistItem(item) ? item.track : item;
	return isTrack(subject) || isArtist(subject) ? subject.rank : undefined;
}

/**
 * What a list keys a row on. A playlist row is addressed by its own position where upstream states
 * one, since the same song sits in a playlist twice and both copies carry one id; everything else is
 * its entity id. Callers pair it with the index anyway, because neither is unique on a page that
 * repeats a recommendation across shelves.
 */
export function entityKey(item: MusicEntity): string {
	if (isPlaylistItem(item)) return item.itemId ?? item.track.id;
	return item.id;
}

/** Flattens a mixed page down to the tracks that can actually be queued. */
export function toTracks(items: MusicEntity[]): Track[] {
	return items.map((item) => (isPlaylistItem(item) ? item.track : item)).filter(isTrack);
}

export function entityTitle(item: MusicEntity, m: Messages): string {
	if (isPlaylistItem(item)) return item.track.title;
	if (isPlaylist(item)) return autoPlaylist(item.id, m)?.title ?? item.title;
	return isArtist(item) ? item.name : item.title;
}

export function entityArtwork(item: MusicEntity): string | undefined {
	if (isPlaylistItem(item)) return item.track.artworkUrl;
	if (isPlaylist(item)) return autoPlaylists[item.id.replace(/^VL/, "")]?.artworkUrl ?? item.artworkUrl;
	return item.artworkUrl;
}

/**
 * The playlists every account holds and nobody made, keyed off the one stable, unlocalised thing they
 * carry: the browse id, `LM` for liked music, `SE` for saved episodes and `RDPN` for the newest
 * episodes of every saved show, which a browse response prefixes with `VL`. None of them can be
 * edited, saved to or deleted, which is what every caller tests this for.
 *
 * Upstream draws no cover for the first two, so theirs are the high-resolution ones YouTube Music
 * ships, through the same restricted artwork protocol as every upstream image. `RDPN` states its own.
 */
export function autoPlaylist(
	id: RemoteId,
	m: Messages
): { artworkUrl?: string; author: string; title: string; description?: string } | undefined {
	const auto = autoPlaylists[id.replace(/^VL/, "")];
	return (
		auto && {
			author: m.common.autoGenerated,
			title: m.common[auto.title],
			artworkUrl: auto.artworkUrl,
			description: auto.description && m.common[auto.description],
		}
	);
}

function artworkProxy(url: string) {
	const id = btoa(url).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
	return `nixie://app/artwork/${id}`;
}

/**
 * The cover upstream lists an empty playlist with. The create endpoint answers with an id and nothing
 * to draw, so a playlist made here wears this until the library is read again.
 */
export const emptyPlaylistArtwork = artworkProxy(
	"https://www.gstatic.com/youtube/media/ytm/images/pbg/playlist-empty-state-@576.png"
);

// The wording is a key into the dictionary rather than a string, so the same playlist reads in the
// language the app is drawn in wherever it is named.
const autoPlaylists: Record<
	string,
	{
		artworkUrl?: string;
		title: "likedMusic" | "episodesForLater" | "newEpisodes";
		description?: "likedMusicDescription";
	}
> = {
	LM: {
		title: "likedMusic",
		artworkUrl: artworkProxy("https://www.gstatic.com/youtube/media/ytm/images/pbg/liked-songs-delhi-1200.png"),
		description: "likedMusicDescription",
	},
	SE: {
		title: "episodesForLater",
		artworkUrl: artworkProxy("https://www.gstatic.com/youtube/media/ytm/images/pbg/podcast-queue-delhi-1200.png"),
	},
	RDPN: { title: "newEpisodes" },
};

export function artistNames(artists: Artist[]): string {
	return artists.map((artist) => artist.name).join(", ");
}

export function entitySubtitle(item: MusicEntity, m: Messages): string {
	if (isPlaylistItem(item)) return artistNames(item.track.artists);
	if (isTrack(item) || isAlbum(item)) return artistNames(item.artists);
	// Upstream's own line under an artist's name where it states one, the kind where it does not, so
	// every caller that would otherwise print "Artist" twice keeps testing the subtitle against it.
	if (isArtist(item)) return item.listeners ?? m.common.artist;
	// A search row knows nothing about its length, and "0 tracks" reads as an empty playlist.
	return (
		item.description ??
		item.author ??
		autoPlaylist(item.id, m)?.author ??
		(item.itemCount ? m.common.trackCount(item.itemCount) : "")
	);
}

/**
 * What a page of search results can be organised around. A result names its own artist, and a song
 * also names the release it came from, which is enough to lead with the things someone searching
 * that term was probably reaching for. An id is only claimed when upstream identified one:
 * `artistFrom` leaves it empty for a name it could not link, and an empty id addresses nothing.
 */
export function searchAnchor(top: MusicEntity | undefined): { artistId?: string; from: MusicEntity[] } {
	// A playlist is nobody's release and has no artist, so it anchors nothing.
	if (!top || isPlaylistItem(top) || isPlaylist(top)) return { from: [] };
	if (isArtist(top)) return { artistId: top.id || undefined, from: [] };
	const artist = top.artists[0];
	// The album a song came from, then whoever made it: what the result itself points at, ahead of
	// what merely ranked near it.
	const from = [isTrack(top) ? top.album : undefined, artist].filter((item): item is Album | Artist =>
		Boolean(item?.id)
	);
	return { artistId: artist?.id || undefined, from };
}

/**
 * An artist page lists releases the way YouTube orders them, newest first, which puts anniversary
 * reissues ahead of the records someone searched the name to find. Nothing upstream ranks albums by
 * popularity, but two lists already on the page are ranked: the search results, and the artist's top
 * songs, which each name the release they came from. So whichever of those reaches an album first
 * decides its place, and an album neither mentions keeps upstream's order behind them.
 *
 * A reissue carries its own id, so "American Idiot" ranking well does not lift the anniversary
 * edition with it. That is the point: the ranked signal is what someone actually plays.
 */
export function byPopularity(albums: Album[], ranked: MusicEntity[]): Album[] {
	const rank = new Map<string, number>();
	for (const item of ranked) {
		const id = isTrack(item) ? item.album?.id : isAlbum(item) ? item.id : undefined;
		if (id && !rank.has(id)) rank.set(id, rank.size);
	}
	if (!rank.size) return albums;
	// Sorting is stable, so everything unranked keeps the order it arrived in.
	return [...albums].sort(
		(a, b) => (rank.get(a.id) ?? Number.MAX_SAFE_INTEGER) - (rank.get(b.id) ?? Number.MAX_SAFE_INTEGER)
	);
}

/**
 * What a row is, the way YouTube Music labels one in a mixed list. An album says which kind of
 * release it is when upstream told us, since "Single" and "EP" are what that page will call itself.
 */
export function entityKind(item: MusicEntity, m: Messages): string {
	const track = isPlaylistItem(item) ? item.track : isTrack(item) ? item : undefined;
	if (track) return track.episode ? m.common.episode : m.common.song;
	if (isAlbum(item)) return item.kind ?? m.common.album;
	if (isArtist(item)) return m.common.artist;
	return isPodcast(item) ? m.common.podcast : m.common.playlist;
}

/**
 * The shelves worth opening a feed on, in the order they are wanted. Upstream reorders home between
 * fetches, so these are pinned to the top and everything else keeps the order it arrived in.
 *
 * Matched on the title's opening words, which upstream localises in the session language, so each rank
 * lists the wording of every language the app asks upstream in. A feed in any other wording matches
 * none of them and keeps upstream's own order, which is the honest fallback.
 */
const LEAD_SHELVES = [
	["quick picks", "scelte rapide"],
	["new releases", "nuove uscite"],
	["trending", "di tendenza"],
	["listen again", "ascolta di nuovo"],
	["albums for you", "album per te"],
];

function shelfRank(title: string): number {
	const name = title.toLowerCase();
	const index = LEAD_SHELVES.findIndex((names) => names.some((lead) => name.startsWith(lead)));
	return index === -1 ? LEAD_SHELVES.length : index;
}

/**
 * A home page's shelves. Upstream states them, and the four kind shelves are the fallback for a feed
 * that came back flat.
 *
 * Only the first page of a feed may fall back. A later page synthesising its own "Quick picks" and
 * "Albums" would put a second shelf under each of those headings every time the reader scrolls.
 */
export function homeShelves(page: Page<MusicEntity>, allowFallback: boolean, m: Messages): MusicSection<MusicEntity>[] {
	const sections =
		page.sections?.length || !allowFallback
			? (page.sections ?? [])
			: [
					{ title: m.common.quickPicks, items: page.items.filter(isTrack) },
					{ title: m.common.albums, items: page.items.filter(isAlbum) },
					{ title: m.common.artists, items: page.items.filter(isArtist) },
					{ title: m.common.playlists, items: page.items.filter(isPlaylist) },
				];
	// Sorting is stable, so a shelf none of the lead titles names keeps the place upstream gave it.
	return sections.filter((section) => section.items.length).sort((a, b) => shelfRank(a.title) - shelfRank(b.title));
}

/** The shelves a home feed has grown past its first page, and which feed they belong to. */
export interface GrownFeed {
	key: string;
	shelves: MusicSection<MusicEntity>[];
	next?: string;
}

/**
 * Appends a page to the feed it was requested for. The key is the chip the request was made under,
 * and a mismatch means a chip was tapped while the page was in flight: that page belongs to a feed
 * nobody is looking at any more, so it is dropped rather than appended under the new one. Returning
 * the input unchanged is what makes the guard a pure function instead of an aborted request.
 */
export function appendPage(
	state: GrownFeed | undefined,
	key: string,
	page: Page<MusicEntity> | undefined,
	m: Messages
): GrownFeed {
	if (state && state.key !== key) return state;
	return {
		key,
		shelves: [...(state?.shelves ?? []), ...(page ? homeShelves(page, false, m) : [])],
		// A page that states no continuation ends the feed, and so does one that never arrived.
		next: page?.continuation,
	};
}
